// ==UserScript==
// @author Dmitrii Fediuk (https://upwork.com/fl/mage2pro)
// @grant GM_addStyle
// @homepageURL https://github.com/dmitrii-fediuk/vm/blob/main/s/Upwork/project/list/phrases.js
// @icon https://www.upwork.com/favicon.ico
// @match *://www.upwork.com/nx/search/jobs*
// @name Upwork / Project / List / Phrases
// ==/UserScript==
// 2025-10-05
// 1) https://g.co/gemini/share/ede314ebdbc2
// 2) https://g.co/gemini/share/a3e668c14254
// 3) «Sometimes, when you use more than one userscript on the same web page, they need to run in a particular order.
// You can change the order using the Violentmonkey dashboard.
// Click and drag the bounding box of each script in the list to move it up or down in the list.»
// https://github.com/OpenUserJs/OpenUserJS.org/wiki/Violentmonkey-for-Chrome#user-content-trouble-shooting
// 4) https://g.co/gemini/share/0433ff10fc5f
// 5) https://g.co/gemini/share/049320c5e4e5
['df', 'upwork', 'project', 'list'].reduce((o, k) => o[k] ??= {}, unsafeWindow).phrases = [
	'🚀', '🎯', '🔥', '💡', '📌'
	,'30 minute'
	,'45-Minute'
	,'30 year old speaker'
	,'3D Renderer'
	,'A startup'
	,'ASAP'
	,'Agile'
	,'Android'
	,'Animation Expert'
	,'Artist'
	,'Become part of our'
	,'Betting'
	,'Blogger'
	,'Brand Communication'
	,'Brand Identity'
	,'Brand Partnership'
	,'Business Development'
	,'Business Startup'
	,'Calendly'
	,'Call to discuss'
	,'Campaign'
	,'Career advice'
	,'CFO'
	,'Chemist'
	,'Circuit'
	,'CISO'
	,'CMO'
	,'Coaching'
	,'Cold Calling'
	,'Cold Calls'
	,'Cold Email'
	,'Comic Book'
	,'Communications Specialist'
	,'Company Logo'
	,'Competitive salary'
	,'Co-owner'
	,'Confluence'
	,'Consultation'
	,'Content Creation'
	,'Content Writer'
	,'Copywriter'
	,'Cost optimization'
	,'Cost-effective'
	,'CPA'
	,'CRO'
	,'Cybersecurity strategy'
	,'Dating App'
	,'Deadline'
	,'Dermatologist'
	,'Design Expert'
	,'Development Agency'
	,'Digital Advertiser'
	,'Digital Advertising'
	,'Digital Course'
	,'Digital Marketing'
	,'Digital Transformation'
	,'Dispute Resolution'
	,'Dynamic team'
	,'Email Marketing'
	,'Entwickler'
	,'Facebook'
	,'Figma'
	,'FinOps'
	,'Financial Model'
	,'Financial Plan'
	,'Financial Report'
	,'Food Formulator'
	,'Footage'
	,'Founder'
	,'Fractional COO'
	,'Fractional CTO'
	,'Fundraising'
	,'Google Ads'
	,'Google Tag Manager'
	,'Grant Research'
	,'Grant Writer'
	,'Grant Writing'
	,'Guest Poster'
	,'Guest Speaker'
	,'Head of Marketing'
	,'Help me'
	,'High Ticket Closer'
	,'How to Apply'
	,'Hubspot'
	,'iCloud'
	,'Ideal candidate'
	,'Immediate Start'
	,'Immigration'
	,'Innovative'
	,'Instagram'
	,'Interior Design'
	,'Interior Designer'
	,'Interview'
	,'Interviews'
	,'Investment Banker'
	,'iOS Devices'
	,'I’m developing'
	,'Japanese'
	,'Jira'
	,'Job Responsibilities'
	,'Jobseeker'
	,'Join our'
	,'Join us'
	,'Jump on a call'
	,'iOS application'
	,'Key Responsibilities'
	,'Klaviyo'
	,'Landing Page Designer'
	,'Lead Generation'
	,'Licensed Therapist'
	,'Market Analysis'
	,'Market Research'
	,'Marketer'
	,'Marketing Agency'
	,'Marketing Expert'
	,'Marketing Powerhouse'
	,'Marketing Team'
	,'Mechanical Engineer'
	,'Media Ads'
	,'Media Buyer'
	,'Media Coverage'
	,'Media Expert'
	,'Media Marketing'
	,'Medical Device'
	,'Mentor'
	,'Mentorship'
	,'Meta Ads'
	,'minutes calls'
	,'Mission'
	,'Mobile Platform'
	,'Moderator'
	,'My clients'
	,'My name is'
	,'N8n'
	,'NDA'
	,'Norwegian'
	,'Online courses'
	,'Our client'
	,'Our customers'
	,'Our team'
	,'Outbound calling'
	,'Paid media'
	,'Partnership Opportunity'
	,'Patent Attorney'
	,'Patent Search'
	,'Photographer'
	,'Pitch deck'
	,'Pitchbook'
	,'Post Production'
	,'Potential for equity'
	,'Preparing Proposal'
	,'Professional Proposal'
	,'Promotional Materials'
	,'Promotional Videos'
	,'PPC'
	,'PR Specialist'
	,'Press Release'
	,'Product Research'
	,'Product Testing'
	,'Profit Percentage'
	,'Project Manager'
	,'Proposal Write'
	,'Quick Job'
	,'Recruiting'
	,'Redesign a website'
	,'Referral Partnership'
	,'Relationship Manager'
	,'Revenue Split'
	,'Residential Contractor'
	,'Resume Builder'
	,'Resume Site'
	,'Sales Strategies'
	,'Search Arbitrage'
	,'SEM'
	,'SEO Consultant'
	,'SEO Expert'
	,'SEO Specialist'
	,'Schedule a brief discussion'
	,'Shooting Content'
	,'Shopify Customizations'
	,'Should not take longer than'
	,'Slack'
	,'Slide presentation'
	,'Social Media'
	,'Software consultancy'
	,'Sourcing Specialist'
	,'Standup'
	,'Stock options'
	,'Strategic Partnership'
	,'Structural Engineer'
	,'Supplement Manufacturer'
	,'T-Shirt Design'
	,'Tax Optimization'
	,'Tax Structures'
	,'Teach me'
	,'Team meeting'
	,'Team of development professionals'
	,'Telecom'
	,'The candidate should provide'
	,'The ideal freelancer'
	,'TikTok'
	,'to partner with'
	,'Trading'
	,'Trainer'
	,'Transgender'
	,'U.S.-based lawyer'
	,'Urgent'
	,'Urgently'
	,'Venture Researcher'
	,'Video Content Creator'
	,'Videographer'
	,'Visual Identity'
	,'Voice'
	,'Voiceover'
	,'We are an accomplished team'
	,'We have developed'
	,'We only hire'
	,'Web Designer'
	,'Web3'
	,'Webflow Designer'
	,'Well funded'
	,'Whatsapp'
	,'Work with a team'
	,'Workshop'
	,'You will be responsible'
	,'Your expertise will be crucial'
	,'Your expertise will help us'
	,'Your insights will help us'
	,'YouTube Thumbnail'
	,'Zoom'
];