// ==UserScript==
// @author Dmitrii Fediuk (https://upwork.com/fl/mage2pro)
// @grant GM_addStyle
// @homepageURL https://github.com/dmitrii-fediuk/vm/blob/main/s/Upwork/project/list/tags.js
// @icon https://www.upwork.com/favicon.ico
// @match *://www.upwork.com/nx/search/jobs*
// @name Upwork / Project / List / Tags
// ==/UserScript==
// 2025-10-05
// 1) https://g.co/gemini/share/ede314ebdbc2
// 2) https://g.co/gemini/share/a3e668c14254
// 3) «Sometimes, when you use more than one userscript on the same web page, they need to run in a particular order.
// You can change the order using the Violentmonkey dashboard.
// Click and drag the bounding box of each script in the list to move it up or down in the list.»
// https://github.com/OpenUserJs/OpenUserJS.org/wiki/Violentmonkey-for-Chrome#user-content-trouble-shooting
// 4) https://g.co/gemini/share/0433ff10fc5f
// 5) https://g.co/gemini/share/049320c5e4e5
['df', 'upwork', 'project', 'list'].reduce((o, k) => o[k] ??= {}, unsafeWindow).tags = [
	'2D Animation'
	,'2D Illustration'
	,'3D Animation'
	,'3D Design'
	,'3D Floor Plan'
	,'3D Modeling'
	,'3D Rendering'
	,'A/B Testing'
	,'AI Video Generation'
	,'AI Video Generator'
	,'AI-Generated Video'
	,'Acting'
	,'Adobe After Effects'
	,'Adobe Captivate'
	,'Adobe Illustrator'
	,'Adobe InDesign'
	,'Adobe Lightroom'
	,'Adobe Photoshop'
	,'Agile Project Management'
	,'Amazon Listing Optimization'
	,'Android'
	,'Android App Development'
	,'Animated Environment'
	,'Animation'
	,'Architectural Design'
	,'Architectural Rendering'
	,'Art & Design'
	,'Art Direction'
	,'Articulate Storyline'
	,'Audience Segmentation & Targeting'
	,'Audio Engineering'
	,'Audio Production'
	,'AutoCAD Civil 3D'
	,'Autodesk Fusion 360'
	,'Autodesk Revit'
	,'B2B Lead Generation'
	,'B2B Marketing'
	,'Biochemistry'
	,'Biology'
	,'Blender'
	,'Blockchain Development'
	,'Blockchain'
	,'Blog Writing'
	,'Bookkeeping'
	,'Brand Guidelines'
	,'Brand Identity Design'
	,'Bubble.io'
	,'Business Coaching'
	,'Business Presentation'
	,'Business Proposal Writing'
	,'Buying'
	,'Canva'
	,'Career Coaching'
	,'Catalog Design'
	,'CNC Programming'
	,'Campaign Management'
	,'Character Animation'
	,'Character Design'
	,'Chart Presentation'
	,'Chemistry'
	,'Children\'s Book Illustration'
	,'Circuit Design'
	,'Civil Engineering'
	,'Clip Studio Paint'
	,'Coaching'
	,'Cold Call'
	,'Cold Calling'
	,'Comedy Writing'
	,'Communication Etiquette'
	,'Content Creation'
	,'Content Marketing Strategy'
	,'Content SEO'
	,'Content Strategy'
	,'Content Writing'
	,'Conversion Rate Optimization'
	,'Copywriting'
	,'Cover Art Thumbnail'
	,'Creative Strategy'
	,'Creative Writing'
	,'Crowdfunding'
	,'Crowdfunding Campaign'
	,'Cryptocurrency'
	,'Customer Care'
	,'Customer Service'
	,'Customer Service Training'
	,'DApps'
	,'DaVinci Resolve'
	,'Dental Care'
	,'Dentistry'
	,'Digital Project Management'
	,'Drafting'
	,'Dropshipping'
	,'ESL Teaching'
	,'Editorial Writing'
	,'Electrical Engineering'
	,'Elementor'
	,'Email Automation'
	,'Email Campaign Setup'
	,'Email Communication'
	,'Email Copywriting'
	,'Email Marketing Strategy'
	,'Email Marketing'
	,'Email Outreach'
	,'English Tutoring'
	,'English'
	,'Environment & Green Technology'
	,'Event Management'
	,'Event Planning'
	,'Event Setup'
	,'Executive Support'
	,'Exterior Rendering'
	,'Facebook Ads Manager'
	,'Facebook Advertising'
	,'Fashion Consultation'
	,'Fashion Design'
	,'Figma'
	,'Film Editing'
	,'Financial Analysis'
	,'Financial Modeling'
	,'Financial Projection'
	,'Floor Plan Design'
	,'Game Development'
	,'Google Ad Manager'
	,'Google Ads'
	,'Google My Business Listing'
	,'Google Review'
	,'Grant Writing'
	,'Graphic Design'
	,'HARO Link Building'
	,'HighLevel'
	,'HubSpot'
	,'Human Resource Management'
	,'Illustration'
	,'Influencer Outreach'
	,'Instagram'
	,'Interior Design'
	,'Internet Marketing'
	,'iOS'
	,'iPad App Development'
	,'Java'
	,'Knitwear'
	,'Land Surveying'
	,'Landing Page'
	,'Lead Generation Analysis'
	,'Lead Generation Content Creation'
	,'Lead Generation Strategy'
	,'Lead Generation'
	,'Life Coaching'
	,'Line Drawing'
	,'LinkedIn'
	,'LinkedIn Recruiting'
	,'Live Interpretation'
	,'Looker Studio'
	,'Maxon Cinema 4D'
	,'MQL 4'
	,'ManyChat'
	,'Make.com'
	,'Market Analysis'
	,'Market Research'
	,'Marketing'
	,'Marketing Analytics'
	,'Marketing Automation'
	,'Marketing Strategy'
	,'Mechanical Engineering'
	,'Media Buying'
	,'Medical Equipment & Supplies'
	,'Meta Quest'
	,'MetaTrader 4'
	,'MetaTrader 5'
	,'Microsoft PowerPoint'
	,'Mobile App'
	,'Mobile App Development'
	,'Modeling'
	,'Motion Graphics'
	,'Narrative'
	,'Newspaper Journalism'
	,'Off-Page SEO'
	,'Online Chat Support'
	,'Outbound Sales'
	,'Outreach Strategy'
	,'PCB Design'
	,'Pay Per Click Advertising'
	,'Penetration Testing'
	,'Personal Branding'
	,'Philosophy'
	,'Photo Editing'
	,'Photo Retouching'
	,'Photography'
	,'Podcast'
	,'Post Template'
	,'Presentation Design'
	,'Price & Quote Negotiation'
	,'Product Design'
	,'Product Photography'
	,'Project Management'
	,'Proofreading'
	,'Public Relations'
	,'Publishing'
	,'QA Testing'
	,'Recruiting'
	,'Replit'
	,'SEMrush'
	,'SEO Backlinking'
	,'SEO Keyword Research'
	,'SEO Strategy'
	,'Sales & Marketing'
	,'Sales'
	,'Sales Call'
	,'Scheduling'
	,'Science Tutoring'
	,'Scriptwriting'
	,'Search Engine Marketing Strategy'
	,'Search Engine Optimization'
	,'Sewing Pattern'
	,'Sewing'
	,'Shopify Development'
	,'Shopify Marketing'
	,'Shopify Theme'
	,'Singing'
	,'Sketch'
	,'Slide Animation'
	,'Slide Transition'
	,'Smartphone'
	,'Social Media Content Creation'
	,'Social Media Design'
	,'Social Media Imagery'
	,'Social Media Management'
	,'Social Media Marketing'
	,'Social Media Marketing Plan'
	,'Social Media Strategy'
	,'SolidWorks'
	,'Sound Mixing'
	,'Sourcing'
	,'Spring Framework'
	,'Steel Structure'
	,'Stock Market'
	,'Structural Engineering'
	,'Supplier Search'
	,'Teaching English'
	,'Team Management'
	,'Telemarketing'
	,'Test Automation'
	,'Testimonial Video'
	,'Textile Design'
	,'TikTok'
	,'TikTok Ad'
	,'TikTok Marketing'
	,'Trading Automation'
	,'Trading Strategy'
	,'Training'
	,'Translation'
	,'Twitter/X'
	,'UGC'
	,'UI Animation'
	,'UI Graphics'
	,'UI/UX Prototyping'
	,'Unity'
	,'User Experience Design'
	,'User Interface Design'
	,'Video Ad'
	,'Video Commercial'
	,'Video Editing & Production'
	,'Video Editing'
	,'Video Post-Editing'
	,'Video Production'
	,'Videography'
	,'Virtual Assistance'
	,'Virtual Reality'
	,'Voice Acting'
	,'Voice Talent'
	,'YouTube Thumbnail'
	,'Voice-Over'
	,'Web Design'
	,'Webinar'
	,'Wedding Photography'
	,`Web3`
	,'Wix'
	,'Xamarin'
	,'YouTube'
	,'YouTube Ads'
	,'YouTube Automation'
	,'YouTube Marketing'
	,'YouTube Monetization'
	,'Zapier'
	,'Zoom Video Conferencing'
	,'iOS Development'
];