// ==UserScript==
// @author Dmitrii Fediuk (https://upwork.com/fl/mage2pro)
// @grant GM_addStyle
// @homepageURL https://github.com/dmitrii-fediuk/vm/blob/main/s/Upwork/project/list/tags.js
// @icon https://www.upwork.com/favicon.ico
// @match *://www.upwork.com/nx/search/jobs*
// @name Upwork / Project / List / Tags
// ==/UserScript==
// 2025-10-05
// 1) https://g.co/gemini/share/ede314ebdbc2
// 2) https://g.co/gemini/share/a3e668c14254
// 3) «Sometimes, when you use more than one userscript on the same web page, they need to run in a particular order.
// You can change the order using the Violentmonkey dashboard.
// Click and drag the bounding box of each script in the list to move it up or down in the list.»
// https://github.com/OpenUserJs/OpenUserJS.org/wiki/Violentmonkey-for-Chrome#user-content-trouble-shooting
unsafeWindow.df.upwork.project.list.tags = [
	'2D Animation'
	,'3D Design'
	,'3D Modeling'
	,'3D Rendering'
	,'A/B Testing'
	,'AI Video Generation'
	,'AI Video Generator'
	,'AI-Generated Video'
	,'Acting'
	,'Adobe After Effects'
	,'Adobe Illustrator'
	,'Adobe Photoshop'
	,'Amazon Listing Optimization'
	,'Android App Development'
	,'Animation'
	,'Architectural Design'
	,'Art & Design'
	,'Art Direction'
	,'Audience Segmentation & Targeting'
	,'Audio Engineering'
	,'Audio Production'
	,'AutoCAD Civil 3D'
	,'Autodesk Fusion 360'
	,'Autodesk Revit'
	,'Biochemistry'
	,'Biology'
	,'Blockchain'
	,'Blockchain Development'
	,'Blog Writing'
	,'Bubble.io'
	,'Business Proposal Writing'
	,'Buying'
	,'CNC Programming'
	,'Campaign Management'
	,'Chemistry'
	,'Circuit Design'
	,'Cold Calling'
	,'Comedy Writing'
	,'Content Creation'
	,'Content Marketing Strategy'
	,'Content Strategy'
	,'Content Writing'
	,'Conversion Rate Optimization'
	,'Copywriting'
	,'Cover Art Thumbnail'
	,'Creative Strategy'
	,'Creative Writing'
	,'Crowdfunding'
	,'Crowdfunding Campaign'
	,'Cryptocurrency'
	,'Customer Care'
	,'Customer Service'
	,'DApps'
	,'DaVinci Resolve'
	,'Digital Project Management'
	,'Drafting'
	,'Dropshipping'
	,'ESL Teaching'
	,'Electrical Engineering'
	,'Elementor'
	,'Email Automation'
	,'Email Campaign Setup'
	,'Email Communication'
	,'Email Copywriting'
	,'Email Marketing Strategy'
	,'Email Marketing'
	,'English Tutoring'
	,'English'
	,'Event Management'
	,'Event Planning'
	,'Event Setup'
	,'Executive Support'
	,'Exterior Rendering'
	,'Facebook Ads Manager'
	,'Facebook Advertising'
	,'Fashion Design'
	,'Figma'
	,'Film Editing'
	,'Financial Analysis'
	,'Financial Projection'
	,'Google Ads'
	,'Grant Writing'
	,'Graphic Design'
	,'HighLevel'
	,'HubSpot'
	,'Human Resource Management'
	,'Illustration'
	,'Influencer Outreach'
	,'Instagram'
	,'Interior Design'
	,'Internet Marketing'
	,'iOS'
	,'Landing Page'
	,'Lead Generation Analysis'
	,'Lead Generation Content Creation'
	,'Lead Generation Strategy'
	,'Lead Generation'
	,'LinkedIn'
	,'LinkedIn Recruiting'
	,'Live Interpretation'
	,'Looker Studio'
	,'MQL 4'
	,'ManyChat'
	,'Make.com'
	,'Market Analysis'
	,'Market Research'
	,'Marketing Analytics'
	,'Marketing Automation'
	,'Marketing Strategy'
	,'Mechanical Engineering'
	,'Medical Equipment & Supplies'
	,'MetaTrader 5'
	,'Mobile App Development'
	,'Modeling'
	,'Motion Graphics'
	,'Outbound Sales'
	,'Outreach Strategy'
	,'PCB Design'
	,'Pay Per Click Advertising'
	,'Penetration Testing'
	,'Photo Editing'
	,'Photography'
	,'Post Template'
	,'Price & Quote Negotiation'
	,'Product Photography'
	,'Project Management'
	,'Proofreading'
	,'Public Relations'
	,'Publishing'
	,'QA Testing'
	,'Recruiting'
	,'Sales & Marketing'
	,'SEO Backlinking'
	,'SEO Keyword Research'
	,'Sales'
	,'Science Tutoring'
	,'Scriptwriting'
	,'Search Engine Marketing Strategy'
	,'Search Engine Optimization'
	,'Singing'
	,'Sketch'
	,'Smartphone'
	,'Social Media Design'
	,'Social Media Imagery'
	,'Social Media Management'
	,'Social Media Marketing'
	,'Social Media Marketing Plan'
	,'Social Media Strategy'
	,'SolidWorks'
	,'Sound Mixing'
	,'Sourcing'
	,'Spring Framework'
	,'Stock Market'
	,'Structural Engineering'
	,'Supplier Search'
	,'Teaching English'
	,'Telemarketing'
	,'Trading Automation'
	,'Trading Strategy'
	,'Translation'
	,'Twitter/X'
	,'UI Animation'
	,'UI Graphics'
	,'UI/UX Prototyping'
	,'User Experience Design'
	,'User Interface Design'
	,'Video Ad'
	,'Video Commercial'
	,'Video Editing & Production'
	,'Video Editing'
	,'Video Post-Editing'
	,'Video Production'
	,'Videography'
	,'Virtual Assistance'
	,'Voice Acting'
	,'YouTube Thumbnail'
	,'Voice-Over'
	,'Web Design'
	,'Webinar'
	,'Wix'
	,'YouTube'
	,'Zapier'
	,'Zoom Video Conferencing'
	,'iOS Development'
];