// ==UserScript==
// @author Dmitrii Fediuk (https://upwork.com/fl/mage2pro)
// @grant GM_addStyle
// @homepageURL https://github.com/dmitrii-fediuk/vm/blob/main/s/Upwork/project/list/tags.js
// @icon https://www.upwork.com/favicon.ico
// @match *://www.upwork.com/nx/search/jobs*
// @name Upwork / Project / List / Tags
// ==/UserScript==
// 2025-10-05
// 1) https://g.co/gemini/share/ede314ebdbc2
// 2) https://g.co/gemini/share/a3e668c14254
// 3) «Sometimes, when you use more than one userscript on the same web page, they need to run in a particular order.
// You can change the order using the Violentmonkey dashboard.
// Click and drag the bounding box of each script in the list to move it up or down in the list.»
// https://github.com/OpenUserJs/OpenUserJS.org/wiki/Violentmonkey-for-Chrome#user-content-trouble-shooting
// 4) https://g.co/gemini/share/0433ff10fc5f
// 5) https://g.co/gemini/share/049320c5e4e5
['df', 'upwork', 'project', 'list'].reduce((o, k) => o[k] ??= {}, unsafeWindow).tags = [
	'2D Animation'
	,'2D Illustration'
	,'3D Animation'
	,'3D Design'
	,'3D Floor Plan'
	,'3D Modeling'
	,'3D Rendering'
	,'3D Rigging'
	,'A/B Testing'
	,'AI Trading'
	,'AI Video Generation'
	,'AI Video Generator'
	,'AI-Generated Video'
	,'Abstract Logo'
	,'Acting'
	,'Adobe After Effects'
	,'Adobe Captivate'
	,'Adobe Illustrator'
	,'Adobe InDesign'
	,'Adobe Lightroom'
	,'Adobe Photoshop'
	,'Adobe Premiere Pro'
	,'Advertising Strategy'
	,'Affiliate Marketing'
	,'Agile Project Management'
	,'Amazon Advertising Console'
	,'Amazon Listing Optimization'
	,'Amazon Marketing'
	,'Amazon PPC'
	,'Android'
	,'Android App Development'
	,'Animated Environment'
	,'Animation'
	,'Applied Behavior Analysis'
	,'Appointment Setting'
	,'Architectural Design'
	,'Architectural Rendering'
	,'Art & Design'
	,'Art Direction'
	,'Articulate Storyline'
	,'Audience Segmentation & Targeting'
	,'Audio Engineering'
	,'Audio Production'
	,'Audiobook'
	,'AutoCAD Civil 3D'
	,'AutoCAD HVAC Loads Calculations'
	,'Autodesk Fusion 360'
	,'Autodesk Maya'
	,'Autodesk Revit'
	,'B2B Lead Generation'
	,'B2B Marketing'
	,'B2C Marketing'
	,'Biochemistry'
	,'Biology'
	,'Blender'
	,'Blockchain Development'
	,'Blockchain'
	,'Blog Writing'
	,'Bookkeeping'
	,'Brand Guidelines'
	,'Brand Identity Design'
	,'Bubble.io'
	,'Business'
	,'Business Coaching'
	,'Business Presentation'
	,'Business Proposal Writing'
	,'Buying'
	,'CAD Drafting'
	,'CNC Programming'
	,'Campaign Management'
	,'Canva'
	,'Career Coaching'
	,'Catalog Design'
	,'Character Animation'
	,'Character Design'
	,'Chart Presentation'
	,'Chemistry'
	,'Children\'s Book Illustration'
	,'Circuit Design'
	,'Civil Engineering'
	,'Clean Technology'
	,'Client Management'
	,'Clinical Trial'
	,'Clinical Trial Management System'
	,'Clip Studio Paint'
	,'Coaching'
	,'Cold Call'
	,'Cold Calling'
	,'Cold Email'
	,'College Essay'
	,'Combination Mark'
	,'Comedy Writing'
	,'Communication Etiquette'
	,'Communication Skills'
	,'Communications'
	,'Composite Material'
	,'Compositing'
	,'Concept Video'
	,'Construction Estimating'
	,'Content Creation'
	,'Content Development'
	,'Content Marketing'
	,'Content Marketing Strategy'
	,'Content SEO'
	,'Content Strategy'
	,'Content Writing'
	,'Conversion Rate Optimization'
	,'Copyright'
	,'Copyright Prosecution'
	,'Copyright Registration'
	,'Copyright Search'
	,'Copywriting'
	,'Course Creation'
	,'Cover Art Thumbnail'
	,'Creative Strategy'
	,'Creative Writing'
	,'Crowdfunding'
	,'Crowdfunding Campaign'
	,'Cryptocurrency'
	,'Cryptocurrency Mining'
	,'Customer Care'
	,'Customer Service'
	,'Customer Service Training'
	,'DApps'
	,'DaVinci Resolve'
	,'Demo Video'
	,'Dental Care'
	,'Dentistry'
	,'Design for Manufacturing'
	,'Direct Marketing'
	,'Digital Advertising'
	,'Digital Project Management'
	,'Divorce'
	,'Drafting'
	,'Dropshipping'
	,'ESL Teaching'
	,'ESP32'
	,'Ebook Writing'
	,'Econometrics'
	,'Editorial Writing'
	,'Elearning'
	,'Electrical Engineering'
	,'Elementor'
	,'Email & Newsletter'
	,'Email Automation'
	,'Email Campaign Setup'
	,'Email Communication'
	,'Email Copywriting'
	,'Email Design'
	,'Email Marketing Strategy'
	,'Email Marketing'
	,'Email Outreach'
	,'Emblem Logo'
	,'Employment Dispute'
	,'Employment Law'
	,'English Tutoring'
	,'English'
	,'Environment & Green Technology'
	,'Ethical Hacking'
	,'Event Management'
	,'Event Planning'
	,'Event Setup'
	,'Executive Support'
	,'Exterior Rendering'
	,'Facebook Ads Manager'
	,'Facebook Advertising'
	,'Facebook Pixel Setup & Optimization'
	,'Fashion Consultation'
	,'Fashion Design'
	,'Female'
	,'Figma'
	,'Film Editing'
	,'Financial Analysis'
	,'Financial Model'
	,'Financial Modeling'
	,'Financial Projection'
	,'Flipbook'
	,'Flipbook Animation'
	,'Floor Plan Design'
	,'Flutter'
	,'Food & Beverage'
	,'Forex Trading'
	,'Functional Testing'
	,'Fundraising'
	,'Game Development'
	,'Game UI/UX Design'
	,'Gaming NFT'
	,'General Transcription'
	,'German Tutoring'
	,'Ghostwriting'
	,'Google Ad Manager'
	,'Google Ads'
	,'Google My Business Listing'
	,'Google My Business Optimization'
	,'Google Review'
	,'Grant Application'
	,'Grant Writing'
	,'Graphic Design'
	,'Green Technology'
	,'HARO Link Building'
	,'HVAC System Design'
	,'HighLevel'
	,'HubSpot'
	,'Human Resource Management'
	,'Illustration'
	,'Immigration Law'
	,'Industrial Design'
	,'Influencer Outreach'
	,'Instagram'
	,'Interior Design'
	,'Internet Marketing'
	,'Investor Overview'
	,'Java'
	,'Knitwear'
	,'Land Surveying'
	,'Landing Page'
	,'Layout Design'
	,'Lead Generation Analysis'
	,'Lead Generation Content Creation'
	,'Lead Generation Strategy'
	,'Lead Generation'
	,'Lead Nurturing'
	,'Life Coaching'
	,'Line Drawing'
	,'LinkedIn Campaign Manager'
	,'LinkedIn Lead Generation'
	,'LinkedIn Recruiting'
	,'LinkedIn'
	,'Literature'
	,'Live Interpretation'
	,'Logo Design'
	,'Logomark'
	,'Logotype'
	,'Looker Studio'
	,'MQL 4'
	,'MT5'
	,'Magazine Layout'
	,'Make.com'
	,'Management Skills'
	,'Manufacturing & Construction'
	,'ManyChat'
	,'Market Analysis'
	,'Market Research'
	,'Marketing Analytics'
	,'Marketing Automation'
	,'Marketing Management'
	,'Marketing Strategy'
	,'Marketing'
	,'Material Selection'
	,'Materials Knowledge'
	,'Maxon Cinema 4D'
	,'Mechanical Design'
	,'Mechanical Engineering'
	,'Media Buying'
	,'Medical Equipment & Supplies'
	,'Meta Pixel'
	,'Meta Quest'
	,'MetaTrader 4'
	,'MetaTrader 5'
	,'Microsoft Excel'
	,'Microsoft PowerPoint'
	,'Mobile App Development'
	,'Mobile App'
	,'Modeling'
	,'Motion Graphics'
	,'Music & Sound Design'
	,'Narration'
	,'Narrative'
	,'Newspaper Journalism'
	,'Non-Disclosure Agreement'
	,'Notion'
	,'Nursing'
	,'Nursing Management'
	,'Off-Page SEO'
	,'Online Chat Support'
	,'Online Market Research'
	,'Organic Traffic Growth'
	,'Outbound Sales'
	,'Outreach Strategy'
	,'PCB Design'
	,'PPC Campaign Setup & Management'
	,'Patent'
	,'Patent Drawing'
	,'Patent Law'
	,'Patent Preparation'
	,'Pay Per Click Advertising'
	,'Penetration Testing'
	,'Personal Branding'
	,'Philosophy'
	,'Phone Communication'
	,'Phone Support'
	,'Photo Editing'
	,'Photo Retouching'
	,'Photography'
	,'Pixel Art'
	,'Podcast'
	,'Post Template'
	,'PowerPoint Presentation'
	,'Presentation Design'
	,'Price & Quote Negotiation'
	,'Product Development'
	,'Product Design'
	,'Product Photography'
	,'Project Management'
	,'Promotional Video'
	,'Proofreading'
	,'Proposal Writing'
	,'Psychology'
	,'Public Relations'
	,'Publishing'
	,'QA Testing'
	,'Quality Assurance'
	,'Quantum Computing'
	,'Real Estate Financial Modeling'
	,'Real Estate Investment Assistance'
	,'Recruiting'
	,'Replit'
	,'Reputation Management'
	,'Resume'
	,'Resume Development'
	,'Resume Screening'
	,'Resume Writing'
	,'SEMrush'
	,'SEO Audit'
	,'SEO Backlinking'
	,'SEO Competitor Analysis'
	,'SEO Keyword Research'
	,'SEO Strategy'
	,'Sales & Marketing'
	,'Sales Call'
	,'Sales Coaching'
	,'Sales'
	,'Scheduling'
	,'Science Tutoring'
	,'Scriptwriting'
	,'Search Engine Marketing'
	,'Search Engine Marketing Strategy'
	,'Search Engine Optimization'
	,'Sewing Pattern'
	,'Sewing'
	,'Shopify Development'
	,'Shopify Marketing'
	,'Shopify Templates'
	,'Shopify Theme'
	,'Signature Logo'
	,'Singing'
	,'Sketch'
	,'Slide Animation'
	,'Slide Transition'
	,'Smartphone'
	,'Social Media Content Creation'
	,'Social Media Design'
	,'Social Media Imagery'
	,'Social Media Management'
	,'Social Media Marketing Plan'
	,'Social Media Marketing'
	,'Social Media Strategy'
	,'Software QA'
	,'Software Testing'
	,'SolidWorks'
	,'Sound Mixing'
	,'Sourcing'
	,'Spokesperson Video'
	,'Sports'
	,'Spring Framework'
	,'Steel Structure'
	,'Stock Market'
	,'Structural Engineering'
	,'Supplier Search'
	,'Tagalog'
	,'Tagalog to English Translation'
	,'Teaching English'
	,'Teaching Spanish'
	,'Team Management'
	,'Telemarketing'
	,'Test Automation'
	,'Testimonial Video'
	,'Textile Design'
	,'TikTok Ad'
	,'TikTok Marketing'
	,'TikTok'
	,'Time Management'
	,'Trademark Consulting'
	,'Trademark Law'
	,'Trademark Prosecution'
	,'Trading Automation'
	,'Trading Strategy'
	,'Training'
	,'Training & Development'
	,'Translation'
	,'Typing'
	,'Twitter/X'
	,'UGC'
	,'UI Animation'
	,'UI Graphics'
	,'UI/UX Prototyping'
	,'UX & UI'
	,'Unity'
	,'Unreal Engine'
	,'User Experience Design'
	,'User Interface Design'
	,'Video Ad'
	,'Video Commercial'
	,'Video Editing & Production'
	,'Video Editing'
	,'Video Post-Editing'
	,'Video Production'
	,'Videography'
	,'Virtual Assistance'
	,'Virtual Reality'
	,'Voice & Tone Consistency'
	,'Voice Acting'
	,'Voice Recording'
	,'Voice Talent'
	,'Voice-Over Recording'
	,'Voice-Over'
	,'Web Design'
	,'Web Testing'
	,'Webflow'
	,'Webinar'
	,'Wedding Photography'
	,'Wix'
	,'Xamarin'
	,'Young Adult'
	,'YouTube Ads'
	,'YouTube Automation'
	,'YouTube Marketing'
	,'YouTube Monetization'
	,'YouTube Thumbnail'
	,'YouTube'
	,'Zapier'
	,'Zoho Creator'
	,'Zoom Video Conferencing'
	,'eBay Marketing'
	,'eBay Listing'
	,'iOS Development'
	,'iOS'
	,'iPad App Development'
	,`Web3`
];